manifiesto/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Actividad_Industrial__c</fullName>
        <label>Actividad Industrial</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Agricultura</fullName>
                </value>
                <value>
                    <fullName>Ambiental</fullName>
                </value>
                <value>
                    <fullName>Biotecnología</fullName>
                </value>
                <value>
                    <fullName>Clínicas y Hospitales</fullName>
                </value>
                <value>
                    <fullName>Comunicaciones</fullName>
                </value>
                <value>
                    <fullName>Construcción</fullName>
                </value>
                <value>
                    <fullName>Cuidado de la salud</fullName>
                </value>
                <value>
                    <fullName>Electrónica</fullName>
                </value>
                <value>
                    <fullName>Energía</fullName>
                </value>
                <value>
                    <fullName>Entretenimiento</fullName>
                </value>
                <value>
                    <fullName>Fabricación</fullName>
                </value>
                <value>
                    <fullName>Gobierno</fullName>
                </value>
                <value>
                    <fullName>Industria Alimenticia</fullName>
                </value>
                <value>
                    <fullName>Ingenieria</fullName>
                </value>
                <value>
                    <fullName>Maquinaria</fullName>
                </value>
                <value>
                    <fullName>Minería</fullName>
                </value>
                <value>
                    <fullName>Otros</fullName>
                </value>
                <value>
                    <fullName>Productos Químicos</fullName>
                </value>
                <value>
                    <fullName>Recreación</fullName>
                </value>
                <value>
                    <fullName>Retail</fullName>
                </value>
                <value>
                    <fullName>Tecnología</fullName>
                </value>
                <value>
                    <fullName>Telecomunicaciones</fullName>
                </value>
                <value>
                    <fullName>Transporte</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>C_digo_de_Error__c</fullName>
        <description>Visible solo para el Admn y solo lectura</description>
        <label>Código de Error</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CodigoSAP__c</fullName>
        <description>Identificador externo de SAP</description>
        <externalId>true</externalId>
        <label>Código SAP</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Descripci_n__c</fullName>
        <label>Descripción</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Giro__c</fullName>
        <label>Giro</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Mensaje_de_Error__c</fullName>
        <description>Solo visible para el admin del sistema y de solo lectura</description>
        <label>Mensaje de Error</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Oficina_Depto_Otro__c</fullName>
        <label>Oficina/Depto./Otro</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>RUT_Razon_Social__c</fullName>
        <description>Este campo es validado por una regla de validación</description>
        <inlineHelpText>El formato es sin punto y con guión.</inlineHelpText>
        <label>RUT Razón Social</label>
        <length>11</length>
        <required>true</required>
        <type>Text</type>
    </fields>
</CustomObject>

manifiesto/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Budget_Confirmed__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Presupuesto confirmado</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Cantidad_de_Meses__c</fullName>
        <label>Cantidad de Meses</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Centro_Logistico__c</fullName>
        <description>Describe el centro logístico desde donde sale cotización</description>
        <inlineHelpText>Centro logístico desde donde sale la cotización</inlineHelpText>
        <label>Centro Logístico</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>1031</fullName>
                </value>
                <value>
                    <fullName>1034</fullName>
                </value>
                <value>
                    <fullName>1041</fullName>
                </value>
                <value>
                    <fullName>1050</fullName>
                </value>
                <value>
                    <fullName>1051</fullName>
                </value>
                <value>
                    <fullName>1061</fullName>
                </value>
                <value>
                    <fullName>1062</fullName>
                </value>
                <value>
                    <fullName>1064</fullName>
                </value>
                <value>
                    <fullName>1071</fullName>
                </value>
                <value>
                    <fullName>2031</fullName>
                </value>
                <value>
                    <fullName>2041</fullName>
                </value>
                <value>
                    <fullName>2061</fullName>
                </value>
                <value>
                    <fullName>2071</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Ciudad_de_Entrega__c</fullName>
        <label>Ciudad de Entrega</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Comentarios_sobre_razon_de_perdida__c</fullName>
        <label>Comentarios sobre razón de pérdida</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Comuna_de_Entrega__c</fullName>
        <label>Comuna de Entrega</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Condicion_de_venta__c</fullName>
        <label>Condición de venta</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Entregado en cliente</fullName>
                </value>
                <value>
                    <fullName>Puesto oficina</fullName>
                </value>
                <value>
                    <fullName>DDP</fullName>
                </value>
                <value>
                    <fullName>CIF</fullName>
                </value>
                <value>
                    <fullName>FOB</fullName>
                </value>
                <value>
                    <fullName>FCA</fullName>
                </value>
                <value>
                    <fullName>EX-WORK</fullName>
                </value>
                <value>
                    <fullName>CFR</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Direccion_de_Entrega__c</fullName>
        <inlineHelpText>Indica la calle y número de entrega</inlineHelpText>
        <label>Dirección de Entrega</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Discovery_Completed__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Descubrimiento completo</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Loss_Reason__c</fullName>
        <label>Razón de pérdida</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Lost to Competitor</fullName>
                    <label>Perdido por la competencia</label>
                </value>
                <value>
                    <fullName>No Budget / Lost Funding</fullName>
                    <label>Sin presupuesto</label>
                </value>
                <value>
                    <fullName>No Decision / Non-Responsive</fullName>
                    <label>Sin decisión / No responde</label>
                </value>
                <value>
                    <fullName>Price</fullName>
                    <label>Precio</label>
                </value>
                <value>
                    <fullName>Other</fullName>
                    <label>Otro</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Pais_de_Entrega__c</fullName>
        <label>País de Entrega</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ROI_Analysis_Completed__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Análisis de ROI completado</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Region_de_Entrega__c</fullName>
        <label>Región de Entrega</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Región de Arica y Parinacota</fullName>
                </value>
                <value>
                    <fullName>Región de Tarapacá</fullName>
                </value>
                <value>
                    <fullName>Región de Antofagasta</fullName>
                </value>
                <value>
                    <fullName>Región de Atacama</fullName>
                </value>
                <value>
                    <fullName>Región de Coquimbo</fullName>
                </value>
                <value>
                    <fullName>Región de Valparaíso</fullName>
                </value>
                <value>
                    <fullName>Región Metropolitana de Santiago</fullName>
                </value>
                <value>
                    <fullName>Región del Libertador General Bernardo O’Higgins</fullName>
                </value>
                <value>
                    <fullName>Región del Maule</fullName>
                </value>
                <value>
                    <fullName>Región del Ñuble</fullName>
                </value>
                <value>
                    <fullName>Región del Biobío</fullName>
                </value>
                <value>
                    <fullName>Región de La Araucanía</fullName>
                </value>
                <value>
                    <fullName>Región de Los Ríos</fullName>
                </value>
                <value>
                    <fullName>Región de Los Lagos</fullName>
                </value>
                <value>
                    <fullName>Región de Aysén del General Carlos Ibáñez del Campo</fullName>
                </value>
                <value>
                    <fullName>Región de Magallanes y la Antártica Chilena</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Tipo_de_Negocio__c</fullName>
        <label>Tipo de Negocio</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Nacional</fullName>
                </value>
                <value>
                    <fullName>Exportación</fullName>
                </value>
                <value>
                    <fullName>Trading</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Unidad_de_Negocios__c</fullName>
        <label>Unidad de Negocios</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Químicos</fullName>
                </value>
                <value>
                    <fullName>Minería</fullName>
                </value>
                <value>
                    <fullName>Plásticos</fullName>
                </value>
                <value>
                    <fullName>Escuadrón</fullName>
                </value>
                <value>
                    <fullName>Quintero</fullName>
                </value>
                <value>
                    <fullName>Resinas</fullName>
                </value>
                <value>
                    <fullName>Mejillones</fullName>
                </value>
                <value>
                    <fullName>Dilox</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

manifiesto/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Peligrosidad__c</fullName>
        <label>Peligrosidad</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Unidad_de_Medida__c</fullName>
        <label>Unidad de Medida</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>KG</fullName>
                </value>
                <value>
                    <fullName>L</fullName>
                </value>
                <value>
                    <fullName>M3</fullName>
                </value>
                <value>
                    <fullName>Ton</fullName>
                </value>
                <value>
                    <fullName>Hr</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

manifiesto/classes/Oxiquim_Crearprograma_Automatico_Test.cls
@isTest
public class Oxiquim_Crearprograma_Automatico_Test {
	@isTest static void test() {
        Oxiquim_Crearprograma_Automatico.crea_programa(crearOportundidad());
    }  
  
    private static List<Opportunity> crearOportundidad(){
        List<Opportunity> oppList = new List<Opportunity>();
        Datetime output = system.today();
        String todaysDaplazosListte = output.formatGmt('yyyy-MM-dd');        
        Pricebook2 listaPrecios = crearPricebook2();
        Product2 prod = crearProduct2();
        crearPriceBookEntry(prod,listaPrecios);
        Account acc = crearCuenta();
        Opportunity sobj = new Opportunity(
          Name = 'Opp',
          Description = 'Reemplazar pasta de retape de Tapel por pasta Oxifill RM75 en líneas de Tulsa',// Descripción de la oportunidad
          CloseDate = Date.valueOf(todaysDaplazosListte),                                                          // Fecha de cierre
          AccountId = acc.Id,                                                                        // Razón Social
          Unidad_de_Negocios__c = null,                                                              // Unidad de Negocios
          StageName = 'Propuesta Entregada',                                                              // Etapa de la oportunidad
          Centro_Logistico__c = '1061',                                                                   // Centro Logístico
          Probability = 60,                                                                               // Probabilidad (%)
          Condicion_de_venta__c = 'Entregado en cliente',                                                 // Condición de venta
          Amount = 5.00000,                                                                               // Venta Neta Esperada
          CurrencyIsoCode = 'USD',                                                      // Divisa de la oportunidad
          Type = 'Venta Recurrente',                                                                      // Tipo de Venta
          Tipo_de_Negocio__c = 'Nacional',                                                                // Tipo de Negocio
          Direccion_de_Entrega__c = null,                                                                 // Dirección de Entrega
          Comuna_de_Entrega__c = 'Coronel',                                                               // Comuna de Entrega
          Ciudad_de_Entrega__c = 'Coronel',                                                               // Ciudad de Entrega
          Region_de_Entrega__c = 'Región del Biobío',                                                     // Región de Entrega
          Cantidad_de_Meses__c = 12,                                                                    // Cantidad de Meses
          Pais_de_Entrega__c = 'Chile',                                                                   // País de Entrega
          Budget_Confirmed__c = false,                                                                    // Presupuesto confirmado
          Discovery_Completed__c = false,                                                                 // Descubrimiento completo
          ROI_Analysis_Completed__c = false,                                                              // Análisis de ROI completado
          Loss_Reason__c = null,                                                                          // Razón de pérdida
          Comentarios_sobre_razon_de_perdida__c = null,                                                   // Comentarios sobre razón de pérdida
          Pricebook2Id =  Test.getStandardPricebookId()
        );
        insert sobj;
        crearOpportunityLineItemSchedule(crearOportunityLineItem(sobj,prod));
        oppList.add(sobj);
        
        return oppList;
    }
    
    private static OpportunityLineItem crearOportunityLineItem(Opportunity opp,Product2 p){
        OpportunityLineItem oppLineTime = new OpportunityLineItem();
        oppLineTime.OpportunityId = opp.Id;
        oppLineTime.Product2Id = p.Id;
        oppLineTime.Quantity = 1;
        oppLineTime.UnitPrice = 1000;
        
        insert oppLineTime;
        return oppLineTime;
    }
    
    private static void crearOpportunityLineItemSchedule(OpportunityLineItem oppLI){
        OpportunityLineItemSchedule oppLIS = new OpportunityLineItemSchedule();
        oppLIS.OpportunityLineItemId = oppLI.Id; 
        oppLIS.type='Revenue';
        oppLIS.ScheduleDate=system.today();
        oppLIS.Revenue = 1000;
        insert oppLIS;
    }
    
    private static Pricebook2 crearPricebook2(){
        Pricebook2 p = new Pricebook2();
        p.Name = 'Lista de Precios';
        p.IsActive = true;
		//p.IsStandard = true;
        insert p;
        return p;
    }
    
    private static Product2 crearProduct2(){
        Product2 p = new Product2();
        p.Name = 'Producto';
        p.IsActive = true;
        p.Family = 'Acetato';
        //p.StockKeepingUnit
        p.Unidad_de_Medida__c = 'KG';
        p.Peligrosidad__c = '8-1779';
        p.CanUseRevenueSchedule = true;
        insert p;
        return p;
    }
    
    private static void crearPriceBookEntry(Product2 prod,Pricebook2 listaPrecios){
        PricebookEntry p = new PricebookEntry();
        p.Product2Id = prod.Id;
        p.Pricebook2Id = Test.getStandardPricebookId();    
        p.UnitPrice = 1000; 
        p.IsActive = true;
        p.CurrencyIsoCode = 'USD';

        insert p;
        
        /*PricebookEntry pbe = new PricebookEntry(Pricebook2Id = listaPrecios.Id, Product2Id = prod.Id, UnitPrice = 1000, IsActive = true);
        insert pbe;*/
            
    }
    
    private static Account crearCuenta(){
        Account sobj = new Account(
          Name = 'Tulsa S.A.',                   // Razón Social
          RUT_Razon_Social__c = '96664360-9',      // RUT Razón Social
          ParentId = null,                         // Matriz
          Giro__c = 'Fabricación de Tableros',     // Giro
          CodigoSAP__c = null,                     // Código SAP
          Website = null,                          // Sitio Web
          Mensaje_de_Error__c = null,              // Mensaje de Error
          C_digo_de_Error__c = null,               // Código de Error
          CurrencyIsoCode = 'USD',  // Moneda de la cuenta
          Actividad_Industrial__c = null,          // Actividad Industrial
          Ownership = 'Privada',                   // Propiedad
          AnnualRevenue = null,                    // Ingresos anuales
          Descripci_n__c = null,                   // Descripción
          NumberOfEmployees = null,                // Empleados
          Oficina_Depto_Otro__c = null            // Oficina/Depto./Otro
        );
        insert sobj;
        
        return sobj;
    }
}