manifiesto/objects/Plazos_por_Etapa__c.object
<CustomObject>
    <description>Determina plazos para las etapas del caso tipo Reclamos</description>
    <fields>
        <fullName>Caso__c</fullName>
        <label>Caso</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Plazos por Etapa</relationshipLabel>
        <relationshipName>Plazos_por_Etapa</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Fecha_de_Inicio__c</fullName>
        <label>Fecha de Inicio</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Fecha_de_Termino__c</fullName>
        <label>Fecha de Termino</label>
        <type>Date</type>
    </fields>
    <label>Plazo por Etapa</label>
    <nameField>
        <label>Nombre del Plazos por Etapa</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Plazos por Etapa</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

manifiesto/classes/OXIQUIM_FechaTerminoPlazosPorEtapa.cls
public class OXIQUIM_FechaTerminoPlazosPorEtapa {
	
    @InvocableMethod
    public static void establecerFechaTermino(List<Plazos_por_Etapa__c> plazosList) {
        List<Plazos_por_Etapa__c> updatePlazosList = new List<Plazos_por_Etapa__c>();
        System.debug('Caso__r.Id: '+plazosList[0].Caso__c);
        List<Plazos_por_Etapa__c> plazosCasosList = [select id,name,Fecha_de_Termino__c,Fecha_de_Inicio__c,Caso__c from Plazos_por_Etapa__c WHERE Caso__c =: plazosList[0].Caso__c ORDER BY CreatedDate ASC];	
        System.debug('plazosCasosList: '+plazosCasosList);
        Integer numeroDePlazos = plazosCasosList.size();

		  if(plazosCasosList.size()>1){			
				Plazos_por_Etapa__c pe = new Plazos_por_Etapa__c(Id=plazosCasosList[numeroDePlazos-2].Id,
				Fecha_de_Termino__c = plazosCasosList[numeroDePlazos-2].Fecha_de_Inicio__c);
				updatePlazosList.add(pe);
				if(plazosList[0].Name == 'Cerrado'){
					 pe = new Plazos_por_Etapa__c(Id=plazosList[0].Id,
					Fecha_de_Termino__c = plazosList[0].Fecha_de_Inicio__c);
					updatePlazosList.add(pe);
				}
			}
    	update updatePlazosList;
        System.debug('updatePlazosList: '+updatePlazosList);
    }
    
}